# Generated by Django 4.2.1 on 2023-05-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=500)),
                ('title', models.CharField(default='', max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
