# Generated by Django 4.2.1 on 2023-05-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='ndote',
        ),
    ]
