# Generated by Django 4.2.1 on 2023-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default=models.CharField(max_length=500), max_length=20, primary_key=True, serialize=False),
        ),
    ]
